#+TITLE: 他山之石 
#+AUTHOR: 三石
#+DATE: <2017-11-18 Sat>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 

1. 有时候，暂时的失利比暂时的胜利要好很多。
2. 谁都不傻，但谁都有傻的时候。
3. 《三侠五义》义渠人偷东西。《毛骗》第二季第六集44:22。第二季第八集19：11-23：58,27：55-29：59
4. 先让他失望，在给他希望，那样他就深信不疑。《毛骗》第一季，第二集,28:30
5. 心里暗示：一种主观意识上被肯定的假设，不一定有根据。但是由于主观上已经肯定了他的存在，所以在心理上便竭力倾向这项内容。
6. 当一个卧底都不知道自己是卧底的时候，自然毫无破绽。
7. 木秀于林，风必崔之；堆出于岸，流比湍之；行高于人，人必非之。不叫的鹅被杀。应介乎才与不才之间
8. 做一些事情，让自己感觉有信息，然后推而广之，展现在生活的各个方面。
9. 比赛，骑自行车，总是许多人一起比赛时结果由于单独一个人去测试。
10. 像爱自己一样爱世上最平凡的人
11. 尘世的喧嚣比内心的不安更加不堪。有时需要拒绝接受外界的信息。
12. friends. 第三季第十二集
13. First they ignore you. Then they laugh at you. Then they fight you. Then you win.
14. A man is but the product of his thoughts what he thinks, he becomes.
15. 量子纠缠：两个粒子相互纠缠，即使相距遥远，一个粒子的行为将会影响另一个粒子的状态。
16. 选择太多，导致我们选择困难；我们会期望太高，难以满足；即使最终选择了一个很好的，也会认为自己放弃了某些美好的东西。
17. 专注：其实是大脑在过滤其他不需要的东西。大脑前叶过滤的不好就无法专注。
18. 刻意练习：成功成才需要多年刻意的练习。特定的目标；专注，不理会无关的事情；反馈；修正；走出舒适区；评价标准；行之有效的练习方法。
19. 对停止成长的节点保持警惕
20. ego cogito ergo sum -- 我思故我在
21. There isn't time, so brief is life, for bickerings, apologies, heartburnings, calling to account. There is only time
    for loving, and but an instant, so to speak, for that. -- 马克吐温(马克吐温说：“生命如此短暂,我们没有时间去争吵、道
    歉、伤心、斤斤计较,我们只有时间去爱,一切稍纵即逝。”)
22. The good life is built with good relationships. -- 哈佛大学研究。好的人际关系和数量没有关系，质量很重要。自己会认为有一个真正可以依赖的人。
23. You obey all the rules and you lose all the funs.
24. Common sense is not that common -- Voltaire "And this especilly appilies application."
25. Deeply believe in themselves.
26. 王侯将相宁有种乎 -- 陈涉世家
27. Next day tell me what you do differently not what a wonder day.
28. silence is very import. 可以让自己好好思考总结考虑
29. deep breath 三个深呼吸
30. 各种形式的冥想都需要深呼吸，专注一件事情（任何事情都可以），发现无法专注时把自己拉回来。
31. The best learn is by tech.
32. 如果你的潜意识不愿意做一件事情，那么你的潜意识会不知不觉让你做出损害这件事情的动作。所以一定要完全相信自己能够做到，
    否则自信的不足，会变成潜意识的阻碍。
33. Fear is your friend. Fear is an indicator. Sometimes it shows you what you shouldn't do. More often than not it show
    you exactly what you should do. -- Timothy Ferriss
34. What's the worst that can happen?
35. Take the analytical frameworks, the capabilities you have, apply them to old fears. Apply them to very big dreams.
36. The frustration is not that they couldn't achieve their dreams, it's that they were not even able to start chasing
    them. -- TED
37. Life Calendar : 每周使用一个小方格，共 90 年。 格子数并不多，而且我们已经使用了很多。-- TED
38. This long-term kind of procrastination that much less visible and less talked about than the funnier, short-term
    deadline-based kind. It usally suffered quietly and privately. And it can be the source of a huge amount of
    long-term unhappiness, and regrets.
39. Deconstruct 解析-拆分 解构复杂问题的能力


** Rejection
1. In life, rejection is certain. Once you accept this fact, it will be easier to anticipate and to overcome moments of rejection.
2. Detach yourself from the results of a request, and you will become more confident and increase your chance for acceptance, or a "yes."
3. The worst part of rejection is the fear of it. Do not let the fear prevent you from making your request.
4. Rejection is nothing more than someone else's opinion. We should never consider it as truth about ourselves.
5. If we talk to enough people without giving up, a rejection will become an acceptance. 
