#+TITLE: 自我完善 
#+AUTHOR: 三石
#+DATE: <2017-11-18 Sat>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 

* 自信、乐观开朗、有活力、笑
自信打不死的心态活到老。
凡事都要有自信。展现在生活的方方面面。
不要低声下气。
对未来乐观、有热情。
It is not the strongest of the species that survives nor the most intelligent. 
It is the one that is the most adaptable to change. -- Charles Darwin

* 思考
必须要自己思考，形成自己的观点。
行成于思，毁于随。

* 技巧-策略
凡是讲究策略

* 我要喜欢你
始终站在对方的立场，凡是为对方考虑。
像爱自己一样爱世上最平凡的人

* 我是一个蠢货
凡事不要去太多顾及自己的脸面，害怕丢人现眼。这样会在反复思考后放弃很多的机会。想做就去做。
I am a muttonhead, cretin, dumbbell, imbecile.
想到就去做
I just don't embarrass that easily.

* practise
不要太高估天赋的作用。只要坚持学习、练习，你肯定能成功。

* 动机
必须保持强大的动机才能坚持去做一件事。

* 感动自己才能感动别人
你做的事情或者事物自己都没有感觉多牛，怎么可能打动其他人。

* 曾国藩六戒-五勤
1. 久利之事勿为，众争之地勿往
2. 勿以小恶弃人大美，勿以小怨忘人大恩
3. 说人之短乃护己之短，夸己之长乃忌人之长
4. 利可众而不可独，谋可寡而不可众
5. 天下古今之庸人，皆以一懒字致败；天下古今之才人，皆以一傲字致败
6. 凡办大事，以识为主，以才为辅；凡成大事，人某居半，天意居半

7. 身勤
8. 眼勤
9. 手勤
10. 口勤
11. 心勤
业精于勤荒于嬉

* Parkindon's law
The perceived complexity of a task will expand to fill the time you allot it.

* 目光放长远
不要只计较一时的得失。一切朝最终目标看齐。

* Never say never

* 口才
语言的魅力是无穷的--
可以和朋友谈一些自己的伤心往事失败生活，这样才能拉近彼此的关系。
如果只是谈论自己的成功，只会与对方产生更大的距离。

* 选择比努力更重要
像下棋一样，看到一步以后的变化已不易，看到三步，十步之后何其难也。
另外，像自己这样的平凡人，往往一开始并不知道自己将来要做什么。
当自己不清楚要做什么的时候，应该追求优秀，把眼下的事做到最好。
一直追求优秀，拼命提升自己，新的平台出现时，自然会有新的方法，而且你的优秀让你的选择多了很多。
当我们没有那么高瞻远瞩的时候，不妨着眼当下，而不是纠结选择和规划，白白错失提升自己的大号时光。

* 时间
I truly believe this, there is time. Even if we are busy, we have time for what matters. 
And when we focus on what matters, we can build the lives we want in the time we've got.
一周有 *24 * 7 = 168* 小时，8 * 5 = 40 小时上班，8 * 7 = 56 小时睡觉，应然剩余 *62* 小时。
